apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: docker-mailserver
    chart: "docker-mailserver-0.3.0"
    heritage: "Helm"
    release: "docker-mailserver"
  name: docker-mailserver-configs
data:
  ### We are in demo mode, so add in some sample data for quick testing
  postfix-accounts.cf: |
    # A sample user - the password is "password"
    user@example.com|{SHA512-CRYPT}$6$l4023rZnQEy/l0Rg$JeNjAAICB43VAX7GTJ9jeE7DR0LeyR5nU.ftq3c42T5E1IZSuRBqwM8erRh6t0CyIT6aYpBIAopzcQHNUvMV00
  postfix-virtual.cf: "# Intentionally left empty"
  SigningTable: "*@example.com mail._domainkey.example.com"
  KeyTable: "mail._domainkey.example.com example.com:mail:/etc/opendkim/keys/example.com/mail.private"
  TrustedHosts: |
    127.0.0.1
    localhost
  ### End demo mode data
    
  
  postfix-main.cf: |
  
  
    smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rb
l_client bl.spamcop.net
  dovecot-services.cf: |
    service imap-login {
      inet_listener imap {
        
      }  
      inet_listener imaps {
        
      }      
    }    
    service pop3-login {
      inet_listener pop3 {
        
      }
      inet_listener pop3s {
        
      }                        
    }


  80-replication.conf: |
    mail_plugins = $mail_plugins notify replication

    service replicator {
      process_min_avail = 1
      unix_listener replicator-doveadm {
        mode = 0600
        user = docker
      }
    }

    service aggregator {
      fifo_listener replication-notify-fifo {
        user = docker
      }
      unix_listener replication-notify {
        user = docker
      }
    }
    
    doveadm_port = 4117
    doveadm_password = secret

    service doveadm {
      inet_listener {
        port = 4117
        ssl = yes
      }
    }

    plugin {
      #mail_replica = tcp:anotherhost.example.com       # use doveadm_port
      #mail_replica = tcp:anotherhost.example.com:12345 # use port 12345 explicitly
    }

  91-override-sieve.conf: |
    plugin {
      sieve = /var/mail/sieve/%d/%n/.dovecot.sieve
      sieve_dir = /var/mail/sieve/%d/%n/sieve
    }

  am-i-healthy.sh: |
    #!/bin/bash
    # this script is intended to be used by periodic kubernetes liveness probes to ensure that the container
    # (and all its dependent services) is healthy
    clamscan /tmp/docker-mailserver/TrustedHosts && \
    echo "All healthy"
